### ISSUE TITLE
Update supported release to reflect supported kubernetes version

### ISSUE THREAD

**Issue by huangyingting** [chaos-mesh/chaos-mesh.github.io#1]
With PR merged into main branch
https://github.com/chaos-mesh/chaos-mesh/pull/4319

Please help update supported releases for kubernetes version 1.26, 1.27 and 1.28 in below link
https://chaos-mesh.org/supported-releases/

@g1eny0ung , please help, many thanks!

**Comment by g1eny0ung** [comment]
Hi @huangyingting, I've already updated related versions in https://github.com/chaos-mesh/website/pull/412. Are there any problems with it?

**Comment by huangyingting** [comment]
Thanks @g1eny0ung , I think with the merge of https://github.com/chaos-mesh/chaos-mesh/pull/4154, v2.6.3 should already support kubernetes 1.28 version, Microsoft also tested on AKS 1.27, https://learn.microsoft.com/en-us/azure/chaos-studio/chaos-studio-versions#chaos-mesh-compatibility, would it be possible to update doc to address Chaos Mesh version 2.6 support matrix? For example

2.6.3 | Yes | 2024.01.24 | - | 1.20, 1.21, 1.22, 1.23, 1.24, 1.25, 1.26, 1.27 and 1.28

**Comment by g1eny0ung** [comment]
I got it. I added a note above the table for people who want to know whether `v2.6` also supports Kubernetes `1.26-1.28`.

<img width="892" alt="image" src="https://github.com/chaos-mesh/chaos-mesh.github.io/assets/15034155/a118f557-5648-4271-aa2d-35d45f02ce74">

And I will follow your suggestion to append versions to the table.

**Comment by g1eny0ung** [comment]
Done in https://github.com/chaos-mesh/website/commit/5dadb198cc30797e45324da9218a3c20cb48f2d2.
